export const AuthTypes = {
    SIGNIN_PROG: 'SIGNIN_PROG',
    SIGNIN_SUCC: 'SIGNIN_SUCC',
    SIGNIN_FAIL: 'SIGNIN_FAIL',
    SET_USER: 'SET_USER',

    CLEAR_ERROR: 'CLEAR_ERROR',

    SIGNOUT_USER: 'SIGNOUT_USER'
};