export const AuthTypes = {
    SIGNIN_PROG: 'SIGNIN_PROG',
    SIGNIN_SUCC: 'SIGNIN_SUCC',
    SIGNIN_FAIL: 'SIGNIN_FAIL',
    SET_USER: 'SET_USER',

    GET_NEW_ACCESS_TOKEN_PROG: 'GET_NEW_ACCESS_TOKEN_PROG',
    GET_NEW_ACCESS_TOKEN_SUCC: 'GET_NEW_ACCESS_TOKEN_SUCC',
    GET_NEW_ACCESS_TOKEN_FAIL: 'GET_NEW_ACCESS_TOKEN_FAIL',

    CLEAR_ERROR: 'CLEAR_ERROR',

    SIGNOUT_USER: 'SIGNOUT_USER'
};