export const CategoryTypes = {
    GET_CATEGORIES_PROG: 'GET_CATEGORIES_PROG',
    GET_CATEGORIES_SUCC: 'GET_CATEGORIES_SUCC',
    GET_CATEGORIES_FAIL: 'GET_CATEGORIES_FAIL',


    ADD_CATEGORY_PROG: 'ADD_CATEGORY_PROG',
    ADD_CATEGORY_SUCC: 'ADD_CATEGORY_SUCC',
    ADD_CATEGORY_FAIL: 'ADD_CATEGORY_FAIL',
};